/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50721
Source Host           : localhost:3306
Source Database       : app_test

Target Server Type    : MYSQL
Target Server Version : 50721
File Encoding         : 65001

Date: 2018-05-15 10:55:30
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for test
-- ----------------------------
DROP TABLE IF EXISTS `test`;
CREATE TABLE `test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_name` varchar(50) DEFAULT NULL,
  `addr` varchar(500) DEFAULT NULL,
  `sex` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3359 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of test
-- ----------------------------
INSERT INTO `test` VALUES ('2715', '3-D Man', null, '1');
INSERT INTO `test` VALUES ('2716', 'Aardwolf', null, '1');
INSERT INTO `test` VALUES ('2717', 'Abdul Alhazred', null, '1');
INSERT INTO `test` VALUES ('2718', 'Abe Brown', null, '1');
INSERT INTO `test` VALUES ('2719', 'Abigail Brand', null, '1');
INSERT INTO `test` VALUES ('2720', 'Abner Jenkins', null, '1');
INSERT INTO `test` VALUES ('2721', 'Abner Little', null, '1');
INSERT INTO `test` VALUES ('2722', 'Abominable Snowman', null, '1');
INSERT INTO `test` VALUES ('2723', 'Abomination', null, '1');
INSERT INTO `test` VALUES ('2724', 'Abominatrix', null, '1');
INSERT INTO `test` VALUES ('2725', 'Abraham Cornelius', null, '1');
INSERT INTO `test` VALUES ('2726', 'Abraxas', null, '1');
INSERT INTO `test` VALUES ('2727', 'Absalom', null, '1');
INSERT INTO `test` VALUES ('2728', 'Absorbing Man', null, '1');
INSERT INTO `test` VALUES ('2729', 'Abyss', null, '1');
INSERT INTO `test` VALUES ('2730', 'Access', null, '1');
INSERT INTO `test` VALUES ('2731', 'Achebe', null, '1');
INSERT INTO `test` VALUES ('2732', 'Achelous', null, '1');
INSERT INTO `test` VALUES ('2733', 'Achilles', null, '1');
INSERT INTO `test` VALUES ('2734', 'Acrobat', null, '1');
INSERT INTO `test` VALUES ('2735', 'Adam II', null, '1');
INSERT INTO `test` VALUES ('2736', 'Adam Warlock', null, '1');
INSERT INTO `test` VALUES ('2737', 'Adam X', null, '1');
INSERT INTO `test` VALUES ('2738', 'Adaptoid', null, '1');
INSERT INTO `test` VALUES ('2739', 'Administrator', null, '1');
INSERT INTO `test` VALUES ('2740', 'Adonis', null, '1');
INSERT INTO `test` VALUES ('2741', 'Adrenazon', null, '1');
INSERT INTO `test` VALUES ('2742', 'Adri Nital', null, '1');
INSERT INTO `test` VALUES ('2743', 'Adrian Corbo', null, '1');
INSERT INTO `test` VALUES ('2744', 'Adrian Toomes', null, '1');
INSERT INTO `test` VALUES ('2745', 'Adrienne Frost', null, '1');
INSERT INTO `test` VALUES ('2746', 'Adversary', null, '1');
INSERT INTO `test` VALUES ('2747', 'Advisor', null, '1');
INSERT INTO `test` VALUES ('2748', 'Aegis', null, '1');
INSERT INTO `test` VALUES ('2749', 'Aelfyre Whitemane', null, '1');
INSERT INTO `test` VALUES ('2750', 'Aero', null, '1');
INSERT INTO `test` VALUES ('2751', 'Aftershock', null, '1');
INSERT INTO `test` VALUES ('2752', 'Agamemnon', null, '1');
INSERT INTO `test` VALUES ('2753', 'Agamotto', null, '1');
INSERT INTO `test` VALUES ('2754', 'Agatha Harkness', null, '1');
INSERT INTO `test` VALUES ('2755', 'Aged Genghis', null, '1');
INSERT INTO `test` VALUES ('2756', 'Agent', null, '1');
INSERT INTO `test` VALUES ('2757', 'Agent Axis', null, '1');
INSERT INTO `test` VALUES ('2758', 'Agent Cheesecake', null, '1');
INSERT INTO `test` VALUES ('2759', 'Agent X', null, '1');
INSERT INTO `test` VALUES ('2760', 'Agent Zero', null, '1');
INSERT INTO `test` VALUES ('2761', 'Aggamon', null, '1');
INSERT INTO `test` VALUES ('2762', 'Aginar', null, '1');
INSERT INTO `test` VALUES ('2763', 'Agon', null, '1');
INSERT INTO `test` VALUES ('2764', 'Agony', null, '1');
INSERT INTO `test` VALUES ('2765', 'Agron', null, '1');
INSERT INTO `test` VALUES ('2766', 'Aguja', null, '1');
INSERT INTO `test` VALUES ('2767', 'Ahab', null, '1');
INSERT INTO `test` VALUES ('2768', 'Ahmet Abdol', null, '1');
INSERT INTO `test` VALUES ('2769', 'Ahura', null, '1');
INSERT INTO `test` VALUES ('2770', 'Air-Walker', null, '1');
INSERT INTO `test` VALUES ('2771', 'Airborne', null, '1');
INSERT INTO `test` VALUES ('2772', 'Aireo', null, '1');
INSERT INTO `test` VALUES ('2773', 'Airstrike', null, '1');
INSERT INTO `test` VALUES ('2774', 'Ajak', null, '1');
INSERT INTO `test` VALUES ('2775', 'Ajax', null, '1');
INSERT INTO `test` VALUES ('2776', 'Ajaxis', null, '1');
INSERT INTO `test` VALUES ('2777', 'Akasha', null, '1');
INSERT INTO `test` VALUES ('2778', 'Akhenaten', null, '1');
INSERT INTO `test` VALUES ('2779', 'Al MacKenzie', null, '1');
INSERT INTO `test` VALUES ('2780', 'Alaris', null, '1');
INSERT INTO `test` VALUES ('2781', 'Albert', null, '1');
INSERT INTO `test` VALUES ('2782', 'Albino', null, '1');
INSERT INTO `test` VALUES ('2783', 'Albion', null, '1');
INSERT INTO `test` VALUES ('2784', 'Alchemy', null, '1');
INSERT INTO `test` VALUES ('2785', 'Alcmena', null, '1');
INSERT INTO `test` VALUES ('2786', 'Aldebron', null, '1');
INSERT INTO `test` VALUES ('2787', 'Aleksander Lukin', null, '1');
INSERT INTO `test` VALUES ('2788', 'Aleksei Sytsevich', null, '1');
INSERT INTO `test` VALUES ('2789', 'Aleta Ogord', null, '1');
INSERT INTO `test` VALUES ('2790', 'Alex', null, '1');
INSERT INTO `test` VALUES ('2791', 'Alex Hayden', null, '1');
INSERT INTO `test` VALUES ('2792', 'Alex Power', null, '1');
INSERT INTO `test` VALUES ('2793', 'Alex Wilder', null, '1');
INSERT INTO `test` VALUES ('2794', 'Alexander Bont', null, '1');
INSERT INTO `test` VALUES ('2795', 'Alexander Goodwin Pierce', null, '1');
INSERT INTO `test` VALUES ('2796', 'Alexander Lexington', null, '1');
INSERT INTO `test` VALUES ('2797', 'Alexander Summers', null, '1');
INSERT INTO `test` VALUES ('2798', 'Algrim the Strong', null, '1');
INSERT INTO `test` VALUES ('2799', 'Alibar', null, '1');
INSERT INTO `test` VALUES ('2800', 'Alicia Masters', null, '1');
INSERT INTO `test` VALUES ('2801', 'Alistair Smythe', null, '1');
INSERT INTO `test` VALUES ('2802', 'Alistaire Stuart', null, '1');
INSERT INTO `test` VALUES ('2803', 'Aliyah Bishop', null, '1');
INSERT INTO `test` VALUES ('2804', 'Alkhema', null, '1');
INSERT INTO `test` VALUES ('2805', 'All-American', null, '1');
INSERT INTO `test` VALUES ('2806', 'Allatou', null, '1');
INSERT INTO `test` VALUES ('2807', 'Allison Blaire', null, '1');
INSERT INTO `test` VALUES ('2808', 'Alpha Ray', null, '1');
INSERT INTO `test` VALUES ('2809', 'Alpha the Ultimate Mutant', null, '1');
INSERT INTO `test` VALUES ('2810', 'Alyosha Kravinoff', null, '1');
INSERT INTO `test` VALUES ('2811', 'Alysande Stuart', null, '1');
INSERT INTO `test` VALUES ('2812', 'Alyssa Moy', null, '1');
INSERT INTO `test` VALUES ('2813', 'Amahl Farouk', null, '1');
INSERT INTO `test` VALUES ('2814', 'Amalgam', null, '1');
INSERT INTO `test` VALUES ('2815', 'Amanda Sefton', null, '1');
INSERT INTO `test` VALUES ('2816', 'Amatsu-Mikaboshi', null, '1');
INSERT INTO `test` VALUES ('2817', 'Amazon', null, '1');
INSERT INTO `test` VALUES ('2818', 'Amber Hunt', null, '1');
INSERT INTO `test` VALUES ('2819', 'Amelia Voght', null, '1');
INSERT INTO `test` VALUES ('2820', 'Amergin', null, '1');
INSERT INTO `test` VALUES ('2821', 'American Ace', null, '1');
INSERT INTO `test` VALUES ('2822', 'American Dream', null, '1');
INSERT INTO `test` VALUES ('2823', 'American Eagle', null, '1');
INSERT INTO `test` VALUES ('2824', 'American Samurai', null, '1');
INSERT INTO `test` VALUES ('2825', 'Americop', null, '1');
INSERT INTO `test` VALUES ('2826', 'Ameridroid', null, '1');
INSERT INTO `test` VALUES ('2827', 'Amiko Kobayashi', null, '1');
INSERT INTO `test` VALUES ('2828', 'Amina Synge', null, '1');
INSERT INTO `test` VALUES ('2829', 'Aminedi', null, '1');
INSERT INTO `test` VALUES ('2830', 'Ammo', null, '1');
INSERT INTO `test` VALUES ('2831', 'Amphibian', null, '1');
INSERT INTO `test` VALUES ('2832', 'Amphibion', null, '1');
INSERT INTO `test` VALUES ('2833', 'Amphibius', null, '1');
INSERT INTO `test` VALUES ('2834', 'Amun', null, '1');
INSERT INTO `test` VALUES ('2835', 'Anaconda', null, '1');
INSERT INTO `test` VALUES ('2836', 'Anais', null, '1');
INSERT INTO `test` VALUES ('2837', 'Analyzer', null, '1');
INSERT INTO `test` VALUES ('2838', 'Anarchist', null, '1');
INSERT INTO `test` VALUES ('2839', 'Ancient One', null, '1');
INSERT INTO `test` VALUES ('2840', 'Andreas von Strucker', null, '1');
INSERT INTO `test` VALUES ('2841', 'Andrew Chord', null, '1');
INSERT INTO `test` VALUES ('2842', 'Andrew Gervais', null, '1');
INSERT INTO `test` VALUES ('2843', 'Android Man', null, '1');
INSERT INTO `test` VALUES ('2844', 'Andromeda', null, '1');
INSERT INTO `test` VALUES ('2845', 'Anelle', null, '1');
INSERT INTO `test` VALUES ('2846', 'Angar the Screamer', null, '1');
INSERT INTO `test` VALUES ('2847', 'Angel', null, '1');
INSERT INTO `test` VALUES ('2848', 'Angel Dust', null, '1');
INSERT INTO `test` VALUES ('2849', 'Angel Face', null, '1');
INSERT INTO `test` VALUES ('2850', 'Angel Salvadore', null, '1');
INSERT INTO `test` VALUES ('2851', 'Angela Cairn', null, '1');
INSERT INTO `test` VALUES ('2852', 'Angela Del Toro', null, '1');
INSERT INTO `test` VALUES ('2853', 'Angelica Jones', null, '1');
INSERT INTO `test` VALUES ('2854', 'Angelo Unuscione', null, '1');
INSERT INTO `test` VALUES ('2855', 'Angler', null, '1');
INSERT INTO `test` VALUES ('2856', 'Ani-Mator', null, '1');
INSERT INTO `test` VALUES ('2857', 'Animus', null, '1');
INSERT INTO `test` VALUES ('2858', 'Ankhi', null, '1');
INSERT INTO `test` VALUES ('2859', 'Annalee', null, '1');
INSERT INTO `test` VALUES ('2860', 'Anne-Marie Cortez', null, '1');
INSERT INTO `test` VALUES ('2861', 'Annex', null, '1');
INSERT INTO `test` VALUES ('2862', 'Annie Ghazikhanian', null, '1');
INSERT INTO `test` VALUES ('2863', 'Annihilus', null, '1');
INSERT INTO `test` VALUES ('2864', 'Anole', null, '1');
INSERT INTO `test` VALUES ('2865', 'Anomalito', null, '1');
INSERT INTO `test` VALUES ('2866', 'Anomaloco', null, '1');
INSERT INTO `test` VALUES ('2867', 'Anomaly', null, '1');
INSERT INTO `test` VALUES ('2868', 'Answer', null, '1');
INSERT INTO `test` VALUES ('2869', 'Ant-Man', null, '1');
INSERT INTO `test` VALUES ('2870', 'Anthropomorpho', null, '1');
INSERT INTO `test` VALUES ('2871', 'Anti-Cap', null, '1');
INSERT INTO `test` VALUES ('2872', 'Anti-Phoenix Force', null, '1');
INSERT INTO `test` VALUES ('2873', 'Anti-Venom', null, '1');
INSERT INTO `test` VALUES ('2874', 'Anti-Vision', null, '1');
INSERT INTO `test` VALUES ('2875', 'Antimatter', null, '1');
INSERT INTO `test` VALUES ('2876', 'Antiphon the Overseer', null, '1');
INSERT INTO `test` VALUES ('2877', 'Antonio', null, '1');
INSERT INTO `test` VALUES ('2878', 'Anubis', null, '1');
INSERT INTO `test` VALUES ('2879', 'Anvil', null, '1');
INSERT INTO `test` VALUES ('2880', 'Anything', null, '1');
INSERT INTO `test` VALUES ('2881', 'Apache Kid', null, '1');
INSERT INTO `test` VALUES ('2882', 'Apalla', null, '1');
INSERT INTO `test` VALUES ('2883', 'Ape', null, '1');
INSERT INTO `test` VALUES ('2884', 'Ape-Man', null, '1');
INSERT INTO `test` VALUES ('2885', 'Ape-X', null, '1');
INSERT INTO `test` VALUES ('2886', 'Apocalypse', null, '1');
INSERT INTO `test` VALUES ('2887', 'Apollo', null, '1');
INSERT INTO `test` VALUES ('2888', 'Apryll', null, '1');
INSERT INTO `test` VALUES ('2889', 'Aquarian', null, '1');
INSERT INTO `test` VALUES ('2890', 'Aquarius', null, '1');
INSERT INTO `test` VALUES ('2891', 'Aqueduct', null, '1');
INSERT INTO `test` VALUES ('2892', 'Arabian Knight', null, '1');
INSERT INTO `test` VALUES ('2893', 'Arachne', null, '1');
INSERT INTO `test` VALUES ('2894', 'Aragorn', null, '1');
INSERT INTO `test` VALUES ('2895', 'Araki', null, '1');
INSERT INTO `test` VALUES ('2896', 'Aralune', null, '1');
INSERT INTO `test` VALUES ('2897', 'Ara?a', null, '1');
INSERT INTO `test` VALUES ('2898', 'Arc', null, '1');
INSERT INTO `test` VALUES ('2899', 'Arcade', null, '1');
INSERT INTO `test` VALUES ('2900', 'Arcademan', null, '1');
INSERT INTO `test` VALUES ('2901', 'Arcanna', null, '1');
INSERT INTO `test` VALUES ('2902', 'Archangel', null, '1');
INSERT INTO `test` VALUES ('2903', 'Archenemy', null, '1');
INSERT INTO `test` VALUES ('2904', 'Archer', null, '1');
INSERT INTO `test` VALUES ('2905', 'Archie Corrigan', null, '1');
INSERT INTO `test` VALUES ('2906', 'Archimage', null, '1');
INSERT INTO `test` VALUES ('2907', 'Architect', null, '1');
INSERT INTO `test` VALUES ('2908', 'Arclight', null, '1');
INSERT INTO `test` VALUES ('2909', 'Arcturus Rann', null, '1');
INSERT INTO `test` VALUES ('2910', 'Ardina', null, '1');
INSERT INTO `test` VALUES ('2911', 'Ardroman', null, '1');
INSERT INTO `test` VALUES ('2912', 'Arena', null, '1');
INSERT INTO `test` VALUES ('2913', 'Ares', null, '1');
INSERT INTO `test` VALUES ('2914', 'Argo', null, '1');
INSERT INTO `test` VALUES ('2915', 'Argus', null, '1');
INSERT INTO `test` VALUES ('2916', 'Ariann', null, '1');
INSERT INTO `test` VALUES ('2917', 'Arides', null, '1');
INSERT INTO `test` VALUES ('2918', 'Ariel', null, '1');
INSERT INTO `test` VALUES ('2919', 'Aries', null, '1');
INSERT INTO `test` VALUES ('2920', 'Arishem the Judge', null, '1');
INSERT INTO `test` VALUES ('2921', 'Arize', null, '1');
INSERT INTO `test` VALUES ('2922', 'Arizona Annie', null, '1');
INSERT INTO `test` VALUES ('2923', 'Arkady Rossovich', null, '1');
INSERT INTO `test` VALUES ('2924', 'Arkon', null, '1');
INSERT INTO `test` VALUES ('2925', 'Arkus', null, '1');
INSERT INTO `test` VALUES ('2926', 'Arlette Truffaut', null, '1');
INSERT INTO `test` VALUES ('2927', 'Arlok', null, '1');
INSERT INTO `test` VALUES ('2928', 'Armadillo', null, '1');
INSERT INTO `test` VALUES ('2929', 'Armageddon', null, '1');
INSERT INTO `test` VALUES ('2930', 'Armand Martel', null, '1');
INSERT INTO `test` VALUES ('2931', 'Armor', null, '1');
INSERT INTO `test` VALUES ('2932', 'Armory', null, '1');
INSERT INTO `test` VALUES ('2933', 'Arnim Zola', null, '1');
INSERT INTO `test` VALUES ('2934', 'Arno Stark', null, '1');
INSERT INTO `test` VALUES ('2935', 'Arranger', null, '1');
INSERT INTO `test` VALUES ('2936', 'Arsenal', null, '1');
INSERT INTO `test` VALUES ('2937', 'Arsenic', null, '1');
INSERT INTO `test` VALUES ('2938', 'Artemis', null, '1');
INSERT INTO `test` VALUES ('2939', 'Arthur Parks', null, '1');
INSERT INTO `test` VALUES ('2940', 'Artie', null, '1');
INSERT INTO `test` VALUES ('2941', 'Artie Maddicks', null, '1');
INSERT INTO `test` VALUES ('2942', 'Arturo Falcones', null, '1');
INSERT INTO `test` VALUES ('2943', 'Asbestos Lady', null, '1');
INSERT INTO `test` VALUES ('2944', 'Asbestos Man', null, '1');
INSERT INTO `test` VALUES ('2945', 'Ashcan', null, '1');
INSERT INTO `test` VALUES ('2946', 'Asmodeus', null, '1');
INSERT INTO `test` VALUES ('2947', 'Asp', null, '1');
INSERT INTO `test` VALUES ('2948', 'Assassin', null, '1');
INSERT INTO `test` VALUES ('2949', 'Asteroth', null, '1');
INSERT INTO `test` VALUES ('2950', 'Astra', null, '1');
INSERT INTO `test` VALUES ('2951', 'Astrid Bloom', null, '1');
INSERT INTO `test` VALUES ('2952', 'Astron', null, '1');
INSERT INTO `test` VALUES ('2953', 'Astronomer', null, '1');
INSERT INTO `test` VALUES ('2954', 'Asylum', null, '1');
INSERT INTO `test` VALUES ('2955', 'Atalanta', null, '1');
INSERT INTO `test` VALUES ('2956', 'Atalon', null, '1');
INSERT INTO `test` VALUES ('2957', 'Athena', null, '1');
INSERT INTO `test` VALUES ('2958', 'Atlas', null, '1');
INSERT INTO `test` VALUES ('2959', 'Atleza', null, '1');
INSERT INTO `test` VALUES ('2960', 'Atom Bob', null, '1');
INSERT INTO `test` VALUES ('2961', 'Atom-Smasher', null, '1');
INSERT INTO `test` VALUES ('2962', 'Att-Lass', null, '1');
INSERT INTO `test` VALUES ('2963', 'Attuma', null, '1');
INSERT INTO `test` VALUES ('2964', 'Atum', null, '1');
INSERT INTO `test` VALUES ('2965', 'Aunt May Parker', null, '1');
INSERT INTO `test` VALUES ('2966', 'Auntie Freeze', null, '1');
INSERT INTO `test` VALUES ('2967', 'Auric', null, '1');
INSERT INTO `test` VALUES ('2968', 'Aurora', null, '1');
INSERT INTO `test` VALUES ('2969', 'Authority', null, '1');
INSERT INTO `test` VALUES ('2970', 'Autolycus', null, '1');
INSERT INTO `test` VALUES ('2971', 'Avalanche', null, '1');
INSERT INTO `test` VALUES ('2972', 'Avarrish', null, '1');
INSERT INTO `test` VALUES ('2973', 'Awesome Android', null, '1');
INSERT INTO `test` VALUES ('2974', 'Axum', null, '1');
INSERT INTO `test` VALUES ('2975', 'Azazel', null, '1');
INSERT INTO `test` VALUES ('2976', 'Baal', null, '1');
INSERT INTO `test` VALUES ('2977', 'Balder', null, '1');
INSERT INTO `test` VALUES ('2978', 'Balor', null, '1');
INSERT INTO `test` VALUES ('2979', 'Balthakk', null, '1');
INSERT INTO `test` VALUES ('2980', 'Bandit', null, '1');
INSERT INTO `test` VALUES ('2981', 'Banshee', null, '1');
INSERT INTO `test` VALUES ('2982', 'Bantam', null, '1');
INSERT INTO `test` VALUES ('2983', 'Baphomet', null, '1');
INSERT INTO `test` VALUES ('2984', 'Barbarus', null, '1');
INSERT INTO `test` VALUES ('2985', 'Barnacle', null, '1');
INSERT INTO `test` VALUES ('2986', 'Baron Blood', null, '1');
INSERT INTO `test` VALUES ('2987', 'Baron Brimstone', null, '1');
INSERT INTO `test` VALUES ('2988', 'Baron Macabre', null, '1');
INSERT INTO `test` VALUES ('2989', 'Baron Mordo', null, '1');
INSERT INTO `test` VALUES ('2990', 'Baron Samedi', null, '1');
INSERT INTO `test` VALUES ('2991', 'Baron Strucker', null, '1');
INSERT INTO `test` VALUES ('2992', 'Baron Von Blitzschlag', null, '1');
INSERT INTO `test` VALUES ('2993', 'Baron Zemo', null, '1');
INSERT INTO `test` VALUES ('2994', 'Baroness Blood', null, '1');
INSERT INTO `test` VALUES ('2995', 'Barracuda', null, '1');
INSERT INTO `test` VALUES ('2996', 'Bart Hamilton', null, '1');
INSERT INTO `test` VALUES ('2997', 'Base', null, '1');
INSERT INTO `test` VALUES ('2998', 'Basil Sandhurst', null, '1');
INSERT INTO `test` VALUES ('2999', 'Basilisk', null, '1');
INSERT INTO `test` VALUES ('3000', 'Bast', null, '1');
INSERT INTO `test` VALUES ('3001', 'Bastion', null, '1');
INSERT INTO `test` VALUES ('3002', 'Batragon', null, '1');
INSERT INTO `test` VALUES ('3003', 'Batroc the Leaper', null, '1');
INSERT INTO `test` VALUES ('3004', 'Battering Ram', null, '1');
INSERT INTO `test` VALUES ('3005', 'Battleaxe', null, '1');
INSERT INTO `test` VALUES ('3006', 'Battlestar', null, '1');
INSERT INTO `test` VALUES ('3007', 'Battletide', null, '1');
INSERT INTO `test` VALUES ('3008', 'Batwing', null, '1');
INSERT INTO `test` VALUES ('3009', 'Beast', null, '1');
INSERT INTO `test` VALUES ('3010', 'Beautiful Dreamer', null, '1');
INSERT INTO `test` VALUES ('3011', 'Bedlam', null, '1');
INSERT INTO `test` VALUES ('3012', 'Bedlam II', null, '1');
INSERT INTO `test` VALUES ('3013', 'Beetle', null, '1');
INSERT INTO `test` VALUES ('3014', 'Beetle II', null, '1');
INSERT INTO `test` VALUES ('3015', 'Behemoth', null, '1');
INSERT INTO `test` VALUES ('3016', 'Bela', null, '1');
INSERT INTO `test` VALUES ('3017', 'Belasco', null, '1');
INSERT INTO `test` VALUES ('3018', 'Belathauzer', null, '1');
INSERT INTO `test` VALUES ('3019', 'Bella Donna', null, '1');
INSERT INTO `test` VALUES ('3020', 'Ben Parker', null, '1');
INSERT INTO `test` VALUES ('3021', 'Ben Reilly', null, '1');
INSERT INTO `test` VALUES ('3022', 'Ben Urich', null, '1');
INSERT INTO `test` VALUES ('3023', 'Benazir Kaur', null, '1');
INSERT INTO `test` VALUES ('3024', 'Benedict Kine', null, '1');
INSERT INTO `test` VALUES ('3025', 'Bengal', null, '1');
INSERT INTO `test` VALUES ('3026', 'Benjamin Jacob Grimm', null, '1');
INSERT INTO `test` VALUES ('3027', 'Bennet du Paris', null, '1');
INSERT INTO `test` VALUES ('3028', 'Benny Beckley', null, '1');
INSERT INTO `test` VALUES ('3029', 'Bentley Wittman', null, '1');
INSERT INTO `test` VALUES ('3030', 'Bereet', null, '1');
INSERT INTO `test` VALUES ('3031', 'Berzerker', null, '1');
INSERT INTO `test` VALUES ('3032', 'Bes', null, '1');
INSERT INTO `test` VALUES ('3033', 'Beta Ray Bill', null, '1');
INSERT INTO `test` VALUES ('3034', 'Bethany Cabe', null, '1');
INSERT INTO `test` VALUES ('3035', 'Betty Brant', null, '1');
INSERT INTO `test` VALUES ('3036', 'Betty Brant Leeds', null, '1');
INSERT INTO `test` VALUES ('3037', 'Betty Ross Banner', null, '1');
INSERT INTO `test` VALUES ('3038', 'Bevatron', null, '1');
INSERT INTO `test` VALUES ('3039', 'Beyonder', null, '1');
INSERT INTO `test` VALUES ('3040', 'Bi-Beast', null, '1');
INSERT INTO `test` VALUES ('3041', 'Bible John', null, '1');
INSERT INTO `test` VALUES ('3042', 'Big Bertha', null, '1');
INSERT INTO `test` VALUES ('3043', 'Big Man', null, '1');
INSERT INTO `test` VALUES ('3044', 'Big Wheel', null, '1');
INSERT INTO `test` VALUES ('3045', 'Bill Foster', null, '1');
INSERT INTO `test` VALUES ('3046', 'Binary', null, '1');
INSERT INTO `test` VALUES ('3047', 'Bird-Brain', null, '1');
INSERT INTO `test` VALUES ('3048', 'Bird-Man', null, '1');
INSERT INTO `test` VALUES ('3049', 'Bishop', null, '1');
INSERT INTO `test` VALUES ('3050', 'Bison', null, '1');
INSERT INTO `test` VALUES ('3051', 'Bizarnage', null, '1');
INSERT INTO `test` VALUES ('3052', 'Black Bolt', null, '1');
INSERT INTO `test` VALUES ('3053', 'Black Box', null, '1');
INSERT INTO `test` VALUES ('3054', 'Black Cat', null, '1');
INSERT INTO `test` VALUES ('3055', 'Black Crow', null, '1');
INSERT INTO `test` VALUES ('3056', 'Black Death', null, '1');
INSERT INTO `test` VALUES ('3057', 'Black Dragon', null, '1');
INSERT INTO `test` VALUES ('3058', 'Black Fox', null, '1');
INSERT INTO `test` VALUES ('3059', 'Black Goliath', null, '1');
INSERT INTO `test` VALUES ('3060', 'Black Jack Tarr', null, '1');
INSERT INTO `test` VALUES ('3061', 'Black King', null, '1');
INSERT INTO `test` VALUES ('3062', 'Black Knight', null, '1');
INSERT INTO `test` VALUES ('3063', 'Black Lama', null, '1');
INSERT INTO `test` VALUES ('3064', 'Black Mamba', null, '1');
INSERT INTO `test` VALUES ('3065', 'Black Marvel', null, '1');
INSERT INTO `test` VALUES ('3066', 'Black Panther', null, '1');
INSERT INTO `test` VALUES ('3067', 'Black Queen', null, '1');
INSERT INTO `test` VALUES ('3068', 'Black Talon', null, '1');
INSERT INTO `test` VALUES ('3069', 'Black Tarantula', null, '1');
INSERT INTO `test` VALUES ('3070', 'Black Tom Cassidy', null, '1');
INSERT INTO `test` VALUES ('3071', 'Black Widow', null, '1');
INSERT INTO `test` VALUES ('3072', 'Blackbird', null, '1');
INSERT INTO `test` VALUES ('3073', 'Blackheart', null, '1');
INSERT INTO `test` VALUES ('3074', 'Blackheath', null, '1');
INSERT INTO `test` VALUES ('3075', 'Blacklash', null, '1');
INSERT INTO `test` VALUES ('3076', 'Blackout', null, '1');
INSERT INTO `test` VALUES ('3077', 'Blackwing', null, '1');
INSERT INTO `test` VALUES ('3078', 'Blackwulf', null, '1');
INSERT INTO `test` VALUES ('3079', 'Blade', null, '1');
INSERT INTO `test` VALUES ('3080', 'Blaquesmith', null, '1');
INSERT INTO `test` VALUES ('3081', 'Blastaar', null, '1');
INSERT INTO `test` VALUES ('3082', 'Blaze', null, '1');
INSERT INTO `test` VALUES ('3083', 'Blazing Skull', null, '1');
INSERT INTO `test` VALUES ('3084', 'Blind Faith', null, '1');
INSERT INTO `test` VALUES ('3085', 'Blind Justice', null, '1');
INSERT INTO `test` VALUES ('3086', 'Blindside', null, '1');
INSERT INTO `test` VALUES ('3087', 'Blindspot', null, '1');
INSERT INTO `test` VALUES ('3088', 'Bling', null, '1');
INSERT INTO `test` VALUES ('3089', 'Blink', null, '1');
INSERT INTO `test` VALUES ('3090', 'Blistik', null, '1');
INSERT INTO `test` VALUES ('3091', 'Blitziana', null, '1');
INSERT INTO `test` VALUES ('3092', 'Blitzkrieger', null, '1');
INSERT INTO `test` VALUES ('3093', 'Blizzard', null, '1');
INSERT INTO `test` VALUES ('3094', 'Blizzard II', null, '1');
INSERT INTO `test` VALUES ('3095', 'Blob', null, '1');
INSERT INTO `test` VALUES ('3096', 'Blockbuster', null, '1');
INSERT INTO `test` VALUES ('3097', 'Bloke', null, '1');
INSERT INTO `test` VALUES ('3098', 'Blonde Phantom', null, '1');
INSERT INTO `test` VALUES ('3099', 'Blood Brothers', null, '1');
INSERT INTO `test` VALUES ('3100', 'Blood Rose', null, '1');
INSERT INTO `test` VALUES ('3101', 'Blood Spider', null, '1');
INSERT INTO `test` VALUES ('3102', 'Bloodaxe', null, '1');
INSERT INTO `test` VALUES ('3103', 'Bloodhawk', null, '1');
INSERT INTO `test` VALUES ('3104', 'Bloodlust', null, '1');
INSERT INTO `test` VALUES ('3105', 'Bloodlust II', null, '1');
INSERT INTO `test` VALUES ('3106', 'Bloodscream', null, '1');
INSERT INTO `test` VALUES ('3107', 'Bloodshed', null, '1');
INSERT INTO `test` VALUES ('3108', 'Bloodsport', null, '1');
INSERT INTO `test` VALUES ('3109', 'Bloodstorm', null, '1');
INSERT INTO `test` VALUES ('3110', 'Bloodtide', null, '1');
INSERT INTO `test` VALUES ('3111', 'Bloodwraith', null, '1');
INSERT INTO `test` VALUES ('3112', 'Blowhard', null, '1');
INSERT INTO `test` VALUES ('3113', 'Blue Bullet', null, '1');
INSERT INTO `test` VALUES ('3114', 'Blue Diamond', null, '1');
INSERT INTO `test` VALUES ('3115', 'Blue Marvel', null, '1');
INSERT INTO `test` VALUES ('3116', 'Blue Shield', null, '1');
INSERT INTO `test` VALUES ('3117', 'Blue Streak', null, '1');
INSERT INTO `test` VALUES ('3118', 'Blur', null, '1');
INSERT INTO `test` VALUES ('3119', 'Bob', null, '1');
INSERT INTO `test` VALUES ('3120', 'Bob Diamond', null, '1');
INSERT INTO `test` VALUES ('3121', 'Bobster', null, '1');
INSERT INTO `test` VALUES ('3122', 'Bogeyman', null, '1');
INSERT INTO `test` VALUES ('3123', 'Bombshell', null, '1');
INSERT INTO `test` VALUES ('3124', 'Boneyard', null, '1');
INSERT INTO `test` VALUES ('3125', 'Bonita Juarez', null, '1');
INSERT INTO `test` VALUES ('3126', 'Boobytrap', null, '1');
INSERT INTO `test` VALUES ('3127', 'Book', null, '1');
INSERT INTO `test` VALUES ('3128', 'Boom Boom', null, '1');
INSERT INTO `test` VALUES ('3129', 'Boom Boy', null, '1');
INSERT INTO `test` VALUES ('3130', 'Boomer', null, '1');
INSERT INTO `test` VALUES ('3131', 'Boomerang', null, '1');
INSERT INTO `test` VALUES ('3132', 'Boomslang', null, '1');
INSERT INTO `test` VALUES ('3133', 'Boost', null, '1');
INSERT INTO `test` VALUES ('3134', 'Bora', null, '1');
INSERT INTO `test` VALUES ('3135', 'Bounty', null, '1');
INSERT INTO `test` VALUES ('3136', 'Bounty Hunter', null, '1');
INSERT INTO `test` VALUES ('3137', 'Bova', null, '1');
INSERT INTO `test` VALUES ('3138', 'Box', null, '1');
INSERT INTO `test` VALUES ('3139', 'Box IV', null, '1');
INSERT INTO `test` VALUES ('3140', 'Brain Cell', null, '1');
INSERT INTO `test` VALUES ('3141', 'Brain Drain', null, '1');
INSERT INTO `test` VALUES ('3142', 'Brain-Child', null, '1');
INSERT INTO `test` VALUES ('3143', 'Brainchild', null, '1');
INSERT INTO `test` VALUES ('3144', 'Bram Velsing', null, '1');
INSERT INTO `test` VALUES ('3145', 'Brass', null, '1');
INSERT INTO `test` VALUES ('3146', 'Bres', null, '1');
INSERT INTO `test` VALUES ('3147', 'Brian Braddock', null, '1');
INSERT INTO `test` VALUES ('3148', 'Brian Falsworth', null, '1');
INSERT INTO `test` VALUES ('3149', 'Brigade', null, '1');
INSERT INTO `test` VALUES ('3150', 'Briquette', null, '1');
INSERT INTO `test` VALUES ('3151', 'Brother Nature', null, '1');
INSERT INTO `test` VALUES ('3152', 'Brother Tode', null, '1');
INSERT INTO `test` VALUES ('3153', 'Brother Voodoo', null, '1');
INSERT INTO `test` VALUES ('3154', 'Brothers Grimm', null, '1');
INSERT INTO `test` VALUES ('3155', 'Bruiser', null, '1');
INSERT INTO `test` VALUES ('3156', 'Brunnhilda', null, '1');
INSERT INTO `test` VALUES ('3157', 'Brutacus', null, '1');
INSERT INTO `test` VALUES ('3158', 'Brute I', null, '1');
INSERT INTO `test` VALUES ('3159', 'Brute II', null, '1');
INSERT INTO `test` VALUES ('3160', 'Brute III', null, '1');
INSERT INTO `test` VALUES ('3161', 'Brynocki', null, '1');
INSERT INTO `test` VALUES ('3162', 'Bucky', null, '1');
INSERT INTO `test` VALUES ('3163', 'Bucky III', null, '1');
INSERT INTO `test` VALUES ('3164', 'Bug', null, '1');
INSERT INTO `test` VALUES ('3165', 'Bulldozer', null, '1');
INSERT INTO `test` VALUES ('3166', 'Bullet', null, '1');
INSERT INTO `test` VALUES ('3167', 'Bullseye', null, '1');
INSERT INTO `test` VALUES ('3168', 'Burner', null, '1');
INSERT INTO `test` VALUES ('3169', 'Burstarr', null, '1');
INSERT INTO `test` VALUES ('3170', 'Bushman', null, '1');
INSERT INTO `test` VALUES ('3171', 'Bushmaster', null, '1');
INSERT INTO `test` VALUES ('3172', 'Bushwacker', null, '1');
INSERT INTO `test` VALUES ('3173', 'Butterball', null, '1');
INSERT INTO `test` VALUES ('3174', 'Buzz', null, '1');
INSERT INTO `test` VALUES ('3175', 'Buzzard', null, '1');
INSERT INTO `test` VALUES ('3176', 'Byrrah', null, '1');
INSERT INTO `test` VALUES ('3177', 'Caber', null, '1');
INSERT INTO `test` VALUES ('3178', 'Cable', null, '1');
INSERT INTO `test` VALUES ('3179', 'Cadaver', null, '1');
INSERT INTO `test` VALUES ('3180', 'Cagliostro', null, '1');
INSERT INTO `test` VALUES ('3181', 'Caiera', null, '1');
INSERT INTO `test` VALUES ('3182', 'Caiman', null, '1');
INSERT INTO `test` VALUES ('3183', 'Cain', null, '1');
INSERT INTO `test` VALUES ('3184', 'Cain Marko', null, '1');
INSERT INTO `test` VALUES ('3185', 'Caleb Alexander', null, '1');
INSERT INTO `test` VALUES ('3186', 'Caliban', null, '1');
INSERT INTO `test` VALUES ('3187', 'Callisto', null, '1');
INSERT INTO `test` VALUES ('3188', 'Calvin Rankin', null, '1');
INSERT INTO `test` VALUES ('3189', 'Calypso', null, '1');
INSERT INTO `test` VALUES ('3190', 'Cameron Hodge', null, '1');
INSERT INTO `test` VALUES ('3191', 'Canasta', null, '1');
INSERT INTO `test` VALUES ('3192', 'Cancer', null, '1');
INSERT INTO `test` VALUES ('3193', 'Candra', null, '1');
INSERT INTO `test` VALUES ('3194', 'Cannonball', null, '1');
INSERT INTO `test` VALUES ('3195', 'Cannonball I', null, '1');
INSERT INTO `test` VALUES ('3196', 'Caprice', null, '1');
INSERT INTO `test` VALUES ('3197', 'Capricorn', null, '1');
INSERT INTO `test` VALUES ('3198', 'Captain America', null, '1');
INSERT INTO `test` VALUES ('3199', 'Captain Atlas', null, '1');
INSERT INTO `test` VALUES ('3200', 'Captain Barracuda', null, '1');
INSERT INTO `test` VALUES ('3201', 'Captain Britain', null, '1');
INSERT INTO `test` VALUES ('3202', 'Captain Fate', null, '1');
INSERT INTO `test` VALUES ('3203', 'Captain Germany', null, '1');
INSERT INTO `test` VALUES ('3204', 'Captain Marvel', null, '1');
INSERT INTO `test` VALUES ('3205', 'Captain Omen', null, '1');
INSERT INTO `test` VALUES ('3206', 'Captain Savage', null, '1');
INSERT INTO `test` VALUES ('3207', 'Captain UK', null, '1');
INSERT INTO `test` VALUES ('3208', 'Captain Ultra', null, '1');
INSERT INTO `test` VALUES ('3209', 'Captain Universe', null, '1');
INSERT INTO `test` VALUES ('3210', 'Captain Wings', null, '1');
INSERT INTO `test` VALUES ('3211', 'Captain Zero', null, '1');
INSERT INTO `test` VALUES ('3212', 'Cardiac', null, '1');
INSERT INTO `test` VALUES ('3213', 'Cardinal', null, '1');
INSERT INTO `test` VALUES ('3214', 'Caregiver', null, '1');
INSERT INTO `test` VALUES ('3215', 'Caretaker', null, '1');
INSERT INTO `test` VALUES ('3216', 'Carl \"Crusher\" Creel', null, '1');
INSERT INTO `test` VALUES ('3217', 'Carlos Lobo', null, '1');
INSERT INTO `test` VALUES ('3218', 'Carmella Unuscione', null, '1');
INSERT INTO `test` VALUES ('3219', 'Carmilla Black', null, '1');
INSERT INTO `test` VALUES ('3220', 'Carnage', null, '1');
INSERT INTO `test` VALUES ('3221', 'Carnivore', null, '1');
INSERT INTO `test` VALUES ('3222', 'Carolyn Parmenter', null, '1');
INSERT INTO `test` VALUES ('3223', 'Carolyn Trainer', null, '1');
INSERT INTO `test` VALUES ('3224', 'Carrie Alexander', null, '1');
INSERT INTO `test` VALUES ('3225', 'Carrion', null, '1');
INSERT INTO `test` VALUES ('3226', 'Carter Ghazikhanian', null, '1');
INSERT INTO `test` VALUES ('3227', 'Cassandra Nova', null, '1');
INSERT INTO `test` VALUES ('3228', 'Cassie Lang', null, '1');
INSERT INTO `test` VALUES ('3229', 'Cassiopea', null, '1');
INSERT INTO `test` VALUES ('3230', 'Cat', null, '1');
INSERT INTO `test` VALUES ('3231', 'Cat-Man', null, '1');
INSERT INTO `test` VALUES ('3232', 'Catiana', null, '1');
INSERT INTO `test` VALUES ('3233', 'Cayman', null, '1');
INSERT INTO `test` VALUES ('3234', 'Cecelia Reyes', null, '1');
INSERT INTO `test` VALUES ('3235', 'Cecilia Reyes', null, '1');
INSERT INTO `test` VALUES ('3236', 'Celestial Madonna', null, '1');
INSERT INTO `test` VALUES ('3237', 'Centennial', null, '1');
INSERT INTO `test` VALUES ('3238', 'Centurion', null, '1');
INSERT INTO `test` VALUES ('3239', 'Centurious', null, '1');
INSERT INTO `test` VALUES ('3240', 'Centurius', null, '1');
INSERT INTO `test` VALUES ('3241', 'Cerberus', null, '1');
INSERT INTO `test` VALUES ('3242', 'Cerebra', null, '1');
INSERT INTO `test` VALUES ('3243', 'Cerise', null, '1');
INSERT INTO `test` VALUES ('3244', 'Cessily Kincaid', null, '1');
INSERT INTO `test` VALUES ('3245', 'Cethlann', null, '1');
INSERT INTO `test` VALUES ('3246', 'Chaka', null, '1');
INSERT INTO `test` VALUES ('3247', 'Challenger', null, '1');
INSERT INTO `test` VALUES ('3248', 'Chamber', null, '1');
INSERT INTO `test` VALUES ('3249', 'Chameleon', null, '1');
INSERT INTO `test` VALUES ('3250', 'Champion of the Universe', null, '1');
INSERT INTO `test` VALUES ('3251', 'Chan Luichow', null, '1');
INSERT INTO `test` VALUES ('3252', 'Chance', null, '1');
INSERT INTO `test` VALUES ('3253', 'Changeling', null, '1');
INSERT INTO `test` VALUES ('3254', 'Chaos', null, '1');
INSERT INTO `test` VALUES ('3255', 'Charcoal', null, '1');
INSERT INTO `test` VALUES ('3256', 'Charles Xavier', null, '1');
INSERT INTO `test` VALUES ('3257', 'Charlie-27', null, '1');
INSERT INTO `test` VALUES ('3258', 'Charon', null, '1');
INSERT INTO `test` VALUES ('3259', 'Chase Stein', null, '1');
INSERT INTO `test` VALUES ('3260', 'Cheetah', null, '1');
INSERT INTO `test` VALUES ('3261', 'Chemistro', null, '1');
INSERT INTO `test` VALUES ('3262', 'Chen Lu', null, '1');
INSERT INTO `test` VALUES ('3263', 'Chi Demon', null, '1');
INSERT INTO `test` VALUES ('3264', 'Chief Examiner', null, '1');
INSERT INTO `test` VALUES ('3265', 'Chimera', null, '1');
INSERT INTO `test` VALUES ('3266', 'Chloe Tran', null, '1');
INSERT INTO `test` VALUES ('3267', 'Choice', null, '1');
INSERT INTO `test` VALUES ('3268', 'Chondu the Mystic', null, '1');
INSERT INTO `test` VALUES ('3269', 'Christopher Summers', null, '1');
INSERT INTO `test` VALUES ('3270', 'Chrome', null, '1');
INSERT INTO `test` VALUES ('3271', 'Chronos', null, '1');
INSERT INTO `test` VALUES ('3272', 'Chthon', null, '1');
INSERT INTO `test` VALUES ('3273', 'Chtylok', null, '1');
INSERT INTO `test` VALUES ('3274', 'Citizen V', null, '1');
INSERT INTO `test` VALUES ('3275', 'Claire Voyant', null, '1');
INSERT INTO `test` VALUES ('3276', 'Claudette St. Croix', null, '1');
INSERT INTO `test` VALUES ('3277', 'Clea', null, '1');
INSERT INTO `test` VALUES ('3278', 'Clearcut', null, '1');
INSERT INTO `test` VALUES ('3279', 'Cletus Kasady', null, '1');
INSERT INTO `test` VALUES ('3280', 'Clint Barton', null, '1');
INSERT INTO `test` VALUES ('3281', 'Clive', null, '1');
INSERT INTO `test` VALUES ('3282', 'Cloak', null, '1');
INSERT INTO `test` VALUES ('3283', 'Cloud', null, '1');
INSERT INTO `test` VALUES ('3284', 'Cloud 9', null, '1');
INSERT INTO `test` VALUES ('3285', 'Clown', null, '1');
INSERT INTO `test` VALUES ('3286', 'Coach', null, '1');
INSERT INTO `test` VALUES ('3287', 'Coachwhip', null, '1');
INSERT INTO `test` VALUES ('3288', 'Cobalt Man', null, '1');
INSERT INTO `test` VALUES ('3289', 'Cobra', null, '1');
INSERT INTO `test` VALUES ('3290', 'Cody Mushumanski Gun Man', null, '1');
INSERT INTO `test` VALUES ('3291', 'Cold War', null, '1');
INSERT INTO `test` VALUES ('3292', 'Coldblood', null, '1');
INSERT INTO `test` VALUES ('3293', 'Coldfire', null, '1');
INSERT INTO `test` VALUES ('3294', 'Collective Man', null, '1');
INSERT INTO `test` VALUES ('3295', 'Collector', null, '1');
INSERT INTO `test` VALUES ('3296', 'Colleen Wing', null, '1');
INSERT INTO `test` VALUES ('3297', 'Colonel', null, '1');
INSERT INTO `test` VALUES ('3298', 'Colonel America', null, '1');
INSERT INTO `test` VALUES ('3299', 'Colossus', null, '1');
INSERT INTO `test` VALUES ('3300', 'Comet', null, '1');
INSERT INTO `test` VALUES ('3301', 'Comet Man', null, '1');
INSERT INTO `test` VALUES ('3302', 'Commander Kraken', null, '1');
INSERT INTO `test` VALUES ('3303', 'Commando', null, '1');
INSERT INTO `test` VALUES ('3304', 'Conan the Barbarian', null, '1');
INSERT INTO `test` VALUES ('3305', 'Condor', null, '1');
INSERT INTO `test` VALUES ('3306', 'Conquer Lord', null, '1');
INSERT INTO `test` VALUES ('3307', 'Conquest', null, '1');
INSERT INTO `test` VALUES ('3308', 'Conquistador', null, '1');
INSERT INTO `test` VALUES ('3309', 'Conrad Josten', null, '1');
INSERT INTO `test` VALUES ('3310', 'Constrictor', null, '1');
INSERT INTO `test` VALUES ('3311', 'Contemplator', null, '1');
INSERT INTO `test` VALUES ('3312', 'Contessa', null, '1');
INSERT INTO `test` VALUES ('3313', 'Contrary', null, '1');
INSERT INTO `test` VALUES ('3314', 'Controller', null, '1');
INSERT INTO `test` VALUES ('3315', 'Copperhead', null, '1');
INSERT INTO `test` VALUES ('3316', 'Copycat', null, '1');
INSERT INTO `test` VALUES ('3317', 'Coral', null, '1');
INSERT INTO `test` VALUES ('3318', 'Cordelia Frost', null, '1');
INSERT INTO `test` VALUES ('3319', 'Cornelius van Lunt', null, '1');
INSERT INTO `test` VALUES ('3320', 'Corona', null, '1');
INSERT INTO `test` VALUES ('3321', 'Corruptor', null, '1');
INSERT INTO `test` VALUES ('3322', 'Corsair', null, '1');
INSERT INTO `test` VALUES ('3323', 'Cottonmouth', null, '1');
INSERT INTO `test` VALUES ('3324', 'Count Abyss', null, '1');
INSERT INTO `test` VALUES ('3325', 'Count Nefaria', null, '1');
INSERT INTO `test` VALUES ('3326', 'Courier', null, '1');
INSERT INTO `test` VALUES ('3327', 'Cowgirl', null, '1');
INSERT INTO `test` VALUES ('3328', 'Crazy Eight', null, '1');
INSERT INTO `test` VALUES ('3329', 'Crime Master', null, '1');
INSERT INTO `test` VALUES ('3330', 'Crime-Buster', null, '1');
INSERT INTO `test` VALUES ('3331', 'Crimebuster', null, '1');
INSERT INTO `test` VALUES ('3332', 'Crimson', null, '1');
INSERT INTO `test` VALUES ('3333', 'Crimson Cavalier', null, '1');
INSERT INTO `test` VALUES ('3334', 'Crimson Commando', null, '1');
INSERT INTO `test` VALUES ('3335', 'Crimson Cowl', null, '1');
INSERT INTO `test` VALUES ('3336', 'Crimson Craig', null, '1');
INSERT INTO `test` VALUES ('3337', 'Crimson Daffodil', null, '1');
INSERT INTO `test` VALUES ('3338', 'Crimson Dynamo', null, '1');
INSERT INTO `test` VALUES ('3339', 'Crimson Dynamo V', null, '1');
INSERT INTO `test` VALUES ('3340', 'Crimson and the Raven', null, '1');
INSERT INTO `test` VALUES ('3341', 'Crippler', null, '1');
INSERT INTO `test` VALUES ('3342', 'Crooked Man', null, '1');
INSERT INTO `test` VALUES ('3343', 'Crossbones', null, '1');
INSERT INTO `test` VALUES ('3344', 'Crossfire', null, '1');
INSERT INTO `test` VALUES ('3345', 'Crown', null, '1');
INSERT INTO `test` VALUES ('3346', 'Crucible', null, '1');
INSERT INTO `test` VALUES ('3347', 'Crusader', null, '1');
INSERT INTO `test` VALUES ('3348', 'Crusher', null, '1');
INSERT INTO `test` VALUES ('3349', 'Crystal', null, '1');
INSERT INTO `test` VALUES ('3350', 'Curtis Connors', null, '1');
INSERT INTO `test` VALUES ('3351', 'Cutthroat', null, '1');
INSERT INTO `test` VALUES ('3352', 'Cybele', null, '1');
INSERT INTO `test` VALUES ('3353', 'Cybelle', null, '1');
INSERT INTO `test` VALUES ('3354', 'Cyber', null, '1');
INSERT INTO `test` VALUES ('3355', 'Cyborg X', null, '1');
INSERT INTO `test` VALUES ('3356', 'Cyclone', '', '2');
